services:
  # 1. 백엔드 서비스
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: creative-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    env_file:
      - ./backend/.env
    restart: always

  # 2. 프런트엔드 서비스
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: creative-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules # 컨테이너 내 node_modules 보호
    restart: always